spring:
  application:
    name: ledgerx
  profiles:
    default: local
  flyway:
    default-schema: ledgerx
    schemas: ledgerx
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: ledgerx

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
    try-it-out-enabled: true
    display-request-duration: true
    filter: true
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: list
    default-models-expand-depth: 1
    default-model-expand-depth: 2
