spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${LEDGERX_DB_URL}
    username: ${LEDGERX_DB_USERNAME}
    password: ${LEDGERX_DB_PASSWORD}

server:
  shutdown: graceful

logging:
  level:
    root: INFO

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

ledgerx:
  kafka:
    consumer-enabled: ${LEDGERX_KAFKA_CONSUMER_ENABLED:true}
  outbox:
    publisher-enabled: ${LEDGERX_OUTBOX_PUBLISHER_ENABLED:true}
